#server:
#  port: ${port:1868}
#spring:
#  application:
#    name: fe-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        username: nacos
#        password: nacos
#        group: FE_BLOG
#        namespace: 192099489
#    gateway:
#      routes:
#        - id: fe-blog
#          uri: lb://fe-blog
#          predicates:
#            - Path=/fe-blog/**
#
#        - id: fe-user
#          uri: lb://fe-user/**
#          predicates:
#            - Path=/fe-user/**
#
#        - id: fe-category
#          uri: lb://fe-category/**
#          predicates:
#            - Path=/fe-category/**
#
#        - id: fe-ornament
#          uri: lb://fe-ornament
#          predicates:
#            - Path=/fe-ornament/**
#  web:
#    resources:
#      static-locations: [ classpath:/static/,classpath:/public,classpath:/resources,classpath:/webapp,file:D:/upload/avatar/,file:D:/upload/media/ ]