server:
  port: 8080
netty:
  port: 8081
  path: /chat
spring:
  data:
    redis:
      host: 192.168.24.128
      port: 6380
    mongodb:
      host: 192.168.24.132
      port: 27017
      username: oldfu
      password: 123456
      database: fe_blog